/*
 * Jada script demonstrating:
 *
 * - how to post-process documentation HTML pages generated by Javadoc
 *
 * - how to share a value across scripts
 */
import java.nio.file.Path
import javax.tools.Diagnostic
import org.apache.commons.lang3.mutable.MutableBoolean
import org.pdfclown.jada.core.proc.JadaFileProcess
import org.pdfclown.jada.core.proc.PageProcessor

printf("\n>>>>>>>>>>>>>>> `%s` script", self.phase)

self.config.getOperation(JadaFileProcess.class).getProcessor(PageProcessor.class)
    .addTweak((org.jsoup.nodes.Document doc, Path file, MutableBoolean changedRef) -> {
        /*
           Append a new paragraph to the class description section of Sample.html if not
           already done!
         */
        if (file.getFileName().toString().equals("Sample.html")
            && doc.selectFirst("p:contains(%s)".formatted(self.phase)) == null) {
            var element = doc.select("section.class-description > div.block:last-child")
            element.append("<p style=\"color:red\">Content dynamically inserted by " +
                "<code>%s</code> script.</p>".formatted(self.phase))
            changedRef.setTrue()
        }

        self.log.print(Diagnostic.Kind.NOTE, self.config.outputDirectory.relativize(file).toString()
            + ' PROCESSED')
    }, "DemoTweak")

self.put("myVar", "HELLO WORLD!")