name: Bug report
description: Report an issue you encountered using Jada Examples.
labels: ["Type: Bug", "Status: Triage"]
assignees:
  - stechio
type: bug
body:
  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: I have [searched](https://github.com/pdfclown/jada-examples/issues?q=is%3Aissue) for duplicate or closed issues
          required: true
        - label: I have read the [Contributing Guidelines](https://github.com/pdfclown/jada-examples/blob/main/docs/CONTRIBUTING.md#bug-reports)
          required: true
        - label: I agree to follow the [Code of Conduct](https://github.com/pdfclown/.github/blob/main/.github/CODE_OF_CONDUCT.md)
          required: true
  - type: dropdown
    id: module
    attributes:
      label: Jada Examples module(s) affected
      multiple: true
      options:
        - jada-examples-basic
        - jada-examples-biblio
        - jada-examples-docreuse
        - jada-examples-include
        - jada-examples-script
        - jada-examples-uml
        - (other)
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Jada Examples version affected
      placeholder: "e.g., 1.3.0"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating system(s) used
      multiple: true
      options:
        - Linux
        - macOS
        - Windows
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: Provide a summary of the issue, including steps to reproduce.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Describe how Jada Examples should behave.
    validations:
      required: true
