import javax.tools.Diagnostic
import org.pdfclown.jada.core.JadaScriptExtension
import org.pdfclown.jada.core.event.MainProcessEvent
import org.pdfclown.jada.core.event.PostProcessEvent
import org.pdfclown.jada.core.proc.JadaFileProcess
import org.pdfclown.jada.core.proc.PageProcessor

/**
 * Jada script extension demonstrating event listening and post-processing of documentation HTML
 * pages generated by javadoc.
 */
class ScriptDemoExtension extends JadaScriptExtension {
    ScriptDemoExtension() {
        println(logMessage('Hello, World'))
    }

    @Override
    void onMainProcess(MainProcessEvent event) {
        println(logMessage('onMainProcess'))

        getConfig().getOperation(JadaFileProcess.class).getProcessor(PageProcessor.class)
            .addTweak((org.jsoup.nodes.Document doc,
                       java.nio.file.Path file,
                       org.apache.commons.lang3.mutable.MutableBoolean changedRef) -> {
                /*
                   Append a new paragraph to the class description section of Sample.html if not
                   already done!
                 */
                if (file.getFileName().toString().equals("Sample.html")
                        && doc.selectFirst("p:contains("
                                + ScriptDemoExtension.class.getSimpleName() + ")") == null) {
                    var element = doc.select("section.class-description > div.block:last-child")
                    element.append("<p style=\"color:red\">Content dynamically inserted by <code>"
                        + ScriptDemoExtension.class.getSimpleName() + "</code>.</p>")
                    changedRef.setTrue()
                }

                getLog().print(Diagnostic.Kind.NOTE, logMessage(getConfig().getOutputDirectory().relativize(file).toString() + ' PROCESSED'))
            }, "DemoTweak")
    }

    @Override
    void onPostProcess(PostProcessEvent event) {
        println(logMessage('onPostProcess'))
    }

    String logMessage(String text) {
        return '\n>>>>>>>>>>>>>>> ' + getClass().getSimpleName() + ': ' + text + '\n'
    }
}
